In [1]:
import os
import pandas as pd
import numpy as np

LOTTO_DIR = './lottonumbers/'

In [2]:
lotto_files = os.listdir(LOTTO_DIR)
lotto_files = pd.Series(lotto_files)

lotto_files.head()

0    2006-12-30.txt
1    2007-01-16.txt
2    2007-02-01.txt
3    2007-02-16.txt
4    2007-03-01.txt
dtype: object

In [3]:
dataframe_lottos = {}

for lotto_file in lotto_files:
    with open(LOTTO_DIR + lotto_file, 'r') as fp:
        data = fp.read()

    dataframe = []
    index = []

    #skip url line by slicing index
    for line in data.split('\n')[1:]:
        splited = line.split(' ')
        index.append(splited[0])

        dataframe.append(splited[1:])
        
    dataframe_lottos[lotto_file] = pd.DataFrame(dataframe, index=index).T

In [4]:
dataframe_lottos['2015-09-01.txt']

,FIRST,THREE_FIRST,THREE_LAST,TWO,NEAR_FIRST,SECOND,THIRD,FOURTH,FIFTH,
0,021094,260,819,89,021093,049585,082869,000467,002045,None
1,None,403,068,None,021095,227915,091929,012922,014668,None
2,None,None,None,None,None,274514,157263,028773,046709,None
3,None,None,None,None,None,312266,218239,133727,060774,None
4,None,None,None,None,None,846674,247194,145163,065680,None
5,None,None,None,None,None,,329358,153683,070660,None
6,None,None,None,None,None,None,482710,155431,079870,None
7,None,None,None,None,None,None,507487,195921,094668,None
8,None,None,None,None,None,None,754988,228222,095982,None
9,None,None,None,None,None,None,999770,247236,112817,None
10,None,None,None,None,None,None,,247871,115416,None
11,None,None,None,None,None,None,None,253769,126796,None
12,None,None,None,None,None,None,None,303019,126960,None
13,None,None,None,None,None,None,None,305294,130145,None
14,None,None,None,None,None,None,None,314291,130336,None
15,None,None,None,None,None,None,None,343066,154153,None
16,None,None,None,None,None,None,None,359022,164919,None
17,None,None,None,None,None,None,None,367990,167353,None
18,None,None,None,None,None,None,None,386389,210760,None
19,None,None,None,None,None,None,None,393421,235597,None
20,None,None,None,None,None,None,None,404137,237676,None
21,None,None,None,None,None,None,None,444269,242105,None
22,None,None,None,None,None,None,None,448038,249674,None
23,None,None,None,None,None,None,None,451399,267949,None
24,None,None,None,None,None,None,None,461489,276768,None
25,None,None,None,None,None,None,None,482564,285834,None
26,None,None,None,None,None,None,None,499959,298071,None
27,None,None,None,None,None,None,None,566718,298414,None
28,None,None,None,None,None,None,None,586820,310209,None
29,None,None,None,None,None,None,None,589288,324915,None
...,...,...,...,...,...,...,...,...,...,...
71,None,None,None,None,None,None,None,None,768549,None
72,None,None,None,None,None,None,None,None,772857,None
73,None,None,None,None,None,None,None,None,784609,None
74,None,None,None,None,None,None,None,None,789425,None
75,None,None,None,None,None,None,None,None,793947,None
76,None,None,None,None,None,None,None,None,800415,None
77,None,None,None,None,None,None,None,None,812413,None
78,None,None,None,None,None,None,None,None,818206,None
79,None,None,None,None,None,None,None,None,829917,None
80,None,None,None,None,None,None,None,None,843607,None
81,None,None,None,None,None,None,None,None,849189,None
82,None,None,None,None,None,None,None,None,871811,None
83,None,None,None,None,None,None,None,None,872795,None
84,None,None,None,None,None,None,None,None,877321,None
85,None,None,None,None,None,None,None,None,886018,None
86,None,None,None,None,None,None,None,None,898948,None
87,None,None,None,None,None,None,None,None,905468,None
88,None,None,None,None,None,None,None,None,906478,None
89,None,None,None,None,None,None,None,None,907877,None
90,None,None,None,None,None,None,None,None,911873,None
91,None,None,None,None,None,None,None,None,920495,None
92,None,None,None,None,None,None,None,None,924699,None
93,None,None,None,None,None,None,None,None,942249,None
94,None,None,None,None,None,None,None,None,954664,None
95,None,None,None,None,None,None,None,None,963887,None
96,None,None,None,None,None,None,None,None,967127,None
97,None,None,None,None,None,None,None,None,973082,None
98,None,None,None,None,None,None,None,None,983116,None
99,None,None,None,None,None,None,None,None,989930,None
100,None,None,None,None,None,None,None,None,,None

In [9]:
# วิเคราะห์ เลขสองตัวท้าย 

last_two_list = []
for key in dataframe_lottos:
    last_two = int(dataframe_lottos[key]['TWO'][0])
    last_two_list.append(last_two)
    
last_two_list = pd.Series(last_two_list)

print("จำนวนงวด:", len(last_two_list))
print(last_two_list.value_counts().head(10))

จำนวนงวด: 296
85    7
5     7
79    7
26    6
98    6
62    6
50    5
25    5
52    5
65    5
dtype: int64

In [8]:
# วิเคราะห์ เลขสามตัวท้าย 

fifth_list = []
for key in dataframe_lottos:
    for idx in range(100):
        fifth = int(dataframe_lottos[key]['FIFTH'][idx])
        fifth_list.append(fifth)
        
fifth_list = pd.Series(fifth_list)

print(fifth_list.value_counts().head(10))

776965    3
136100    3
175370    3
956832    2
134621    2
938536    2
467071    2
550930    2
686899    2
22366     2
dtype: int64